PCOPY_SRC_DIR		:= src/pcopy

PCOPY_BIN			:= bin/pcopy
PCOPY_CFLAG			:= -fPIC -pthread
PCOPY_LD			:= -pthread -lncurses

PCOPY_DEPEND_LIB	:=

PCOPY_CHCKSUM_FILE	:= pcopy.chcksum

PCOPY_LOCALE		:= locale/pcopy

BIN_SYMS			+= PCOPY
